### ISSUE TITLE
bug: unused parameter

### ISSUE THREAD

**Issue by brandonkal** [codefeathers/Promise.object#1]
See first and last highlighted lines:
The start function only accepts and acts on one parameter.

https://github.com/codefeathers/Promise.object/blob/abf53be3fd9f4349d4165072d1ec7e0b4deed0b6/index.js#L25-L31

**Comment by MKRhere** [comment]
Indeed, thanks for noticing. Will fix, along with other issues. Due for a new release anyway.

**Comment by brandonkal** [comment]
It is also worth noting that I found a way to type such a function:

https://github.com/brandonkal/deno-lib/blob/fe94b7b2783776e5052a6a0a95f37e0dff066697/resolve-promise-object.ts#L10-L20

**Comment by brandonkal** [comment]
@MKRhere What other issues are you seeing?

**Comment by MKRhere** [comment]
There is an open bug on deep-cyclic objects. Root cyclic is resolved correctly. I've created a rewrite branch which is not ready yet, but will be soon and is supposed to be a bit more efficient. With the rewrite, this (#1) bug becomes irrelevant, so I might close this issue when it's merged to master.

**Comment by MKRhere** [comment]
I've published an update, and it's on Deno as well now: https://deno.land/x/promise_object
